// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaos8UuWHsq_W_ZoewVmNVGenx_1IWChc',
    appId: '1:773262014984:web:a40414eac96d83f0d3efbd',
    messagingSenderId: '773262014984',
    projectId: 'instagram-clone-ddedd',
    authDomain: 'instagram-clone-ddedd.firebaseapp.com',
    storageBucket: 'instagram-clone-ddedd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3j8iiz-Ood9wntzd9mGo5lsZJmKHUgeg',
    appId: '1:773262014984:android:f665b7c53b25b2bbd3efbd',
    messagingSenderId: '773262014984',
    projectId: 'instagram-clone-ddedd',
    storageBucket: 'instagram-clone-ddedd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCABHJobUGPnxkfOBP9A48UTbHBceS8FrY',
    appId: '1:773262014984:ios:b1769bfdfd2531a6d3efbd',
    messagingSenderId: '773262014984',
    projectId: 'instagram-clone-ddedd',
    storageBucket: 'instagram-clone-ddedd.appspot.com',
    iosClientId: '773262014984-cm7n8otv94oblvi4kgsjt1s2h9ojljjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCABHJobUGPnxkfOBP9A48UTbHBceS8FrY',
    appId: '1:773262014984:ios:b1769bfdfd2531a6d3efbd',
    messagingSenderId: '773262014984',
    projectId: 'instagram-clone-ddedd',
    storageBucket: 'instagram-clone-ddedd.appspot.com',
    iosClientId: '773262014984-cm7n8otv94oblvi4kgsjt1s2h9ojljjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
